import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:shared_preferences/shared_preferences.dart';
void main()=>runApp(const App());
const gold=Color(0xFFD4A62A), black=Color(0xFF111111);
class App extends StatelessWidget{const App({super.key});Widget build(c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'D&S Cleaning Service',theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:gold),useMaterial3:true,appBarTheme:const AppBarTheme(backgroundColor:black,foregroundColor:Colors.white)),home:const Home());}
class It{String d;double q,r;It(this.d,this.q,this.r);double get a=>q*r;Map<String,dynamic> j()=>{'d':d,'q':q,'r':r};factory It.f(Map<String,dynamic>x)=>It(x['d'],(x['q']as num).toDouble(),(x['r']as num).toDouble());}
class Dc{String id,t,c,a,p,date,valid,note;double dis;List<It> items;Dc(this.id,this.t,this.c,this.a,this.p,this.date,this.valid,this.note,this.dis,this.items);double get sub=>items.fold(0,(s,x)=>s+x.a);double get total=>sub-sub*dis/100;Map<String,dynamic>j()=>{'id':id,'t':t,'c':c,'a':a,'p':p,'date':date,'valid':valid,'note':note,'dis':dis,'items':items.map((e)=>e.j()).toList()};factory Dc.f(Map<String,dynamic>x)=>Dc(x['id'],x['t'],x['c'],x['a']??'',x['p']??'',x['date'],x['valid']??'',x['note']??'',(x['dis']as num?)?.toDouble()??0,(x['items']as List).map((e)=>It.f(Map<String,dynamic>.from(e))).toList());}
Future<List<Dc>> load()async{final p=await SharedPreferences.getInstance(),s=p.getString('docs2');if(s==null)return[];return(jsonDecode(s)as List).map((e)=>Dc.f(Map<String,dynamic>.from(e))).toList();}
Future<void> save(List<Dc>x)async{final p=await SharedPreferences.getInstance();await p.setString('docs2',jsonEncode(x.map((e)=>e.j()).toList()));}
class Home extends StatefulWidget{const Home({super.key});State<Home>createState()=>_H();}
class _H extends State<Home>{List<Dc>d=[];void initState(){super.initState();ref();}Future<void>ref()async{d=await load();if(mounted)setState((){});}Future<void>add(String t)async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>Create(t)));ref();}
Future<void>del(Dc x)async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Delete document?'),content:Text('Delete ${x.id}?'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Delete'))]))??false;if(ok){d.removeWhere((e)=>e.id==x.id);await save(d);setState((){});}}
Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('D&S Cleaning Service')),floatingActionButton:FloatingActionButton(backgroundColor:gold,onPressed:()=>add('Invoice'),child:const Icon(Icons.add)),body:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:black,borderRadius:BorderRadius.circular(18)),child:Column(children:[Image.asset('assets/ds_logo.jpg',height:160),const Text('INVOICE & QUOTATION',style:TextStyle(color:gold,fontSize:21,fontWeight:FontWeight.bold))])),const SizedBox(height:12),Row(children:[Expanded(child:FilledButton.tonal(onPressed:()=>add('Invoice'),child:const Text('New Invoice'))),const SizedBox(width:8),Expanded(child:FilledButton.tonal(onPressed:()=>add('Quotation'),child:const Text('New Quotation')))]),const SizedBox(height:18),const Text('Saved Documents',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...d.reversed.map((x)=>Card(child:ListTile(title:Text('${x.id} • ${x.c}'),subtitle:Text('${x.date}${x.valid.isEmpty?'':' | Valid: ${x.valid}'}\nLKR ${NumberFormat('#,##0.00').format(x.total)}'),isThreeLine:true,onTap:()=>pdf(x),trailing:IconButton(icon:const Icon(Icons.delete,color:Colors.red),onPressed:()=>del(x)))))]));}
class Create extends StatefulWidget{final String t;const Create(this.t,{super.key});State<Create>createState()=>_C();}
class _C extends State<Create>{final c=TextEditingController(),a=TextEditingController(),p=TextEditingController(),note=TextEditingController(),desc=TextEditingController(),qty=TextEditingController(text:'1'),rate=TextEditingController(),dis=TextEditingController(text:'0');DateTime date=DateTime.now(),valid=DateTime.now().add(const Duration(days:14));List<It>items=[];double get sub=>items.fold(0,(s,x)=>s+x.a);double get dp=>double.tryParse(dis.text)??0;double get total=>sub-sub*dp/100;
Future<void>pick(bool v)async{final z=await showDatePicker(context:context,initialDate:v?valid:date,firstDate:DateTime(2020),lastDate:DateTime(2100));if(z!=null)setState((){if(v)valid=z;else date=z;});}
void ai(){final q=double.tryParse(qty.text),r=double.tryParse(rate.text);if(desc.text.trim().isEmpty||q==null||r==null)return;setState(()=>items.add(It(desc.text.trim(),q,r)));desc.clear();rate.clear();qty.text='1';}
Future<void>sv()async{if(c.text.trim().isEmpty||items.isEmpty)return;final ds=await load(),n=ds.where((e)=>e.t==widget.t).length+1,id='${widget.t=='Invoice'?'INV':'QTN'}-${n.toString().padLeft(4,'0')}';final x=Dc(id,widget.t,c.text.trim(),a.text.trim(),p.text.trim(),DateFormat('yyyy-MM-dd').format(date),widget.t=='Quotation'?DateFormat('yyyy-MM-dd').format(valid):'',note.text.trim(),dp,List.of(items));ds.add(x);await save(ds);if(mounted){await pdf(x);if(mounted)Navigator.pop(context);}}
Widget f(TextEditingController x,String l,{int lines=1,bool num=false,ValueChanged<String>?ch})=>TextField(controller:x,maxLines:lines,keyboardType:num?TextInputType.number:TextInputType.text,onChanged:ch,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder()));
Widget dt(String l,DateTime x,VoidCallback z)=>Card(child:ListTile(title:Text(l),subtitle:Text(DateFormat('yyyy-MM-dd').format(x)),trailing:const Icon(Icons.calendar_month),onTap:z));
Widget build(ctx)=>Scaffold(appBar:AppBar(title:Text('New ${widget.t}')),body:ListView(padding:const EdgeInsets.all(16),children:[dt('Custom Date',date,()=>pick(false)),if(widget.t=='Quotation')dt('Quotation Valid Until',valid,()=>pick(true)),const SizedBox(height:10),f(c,'Customer Name'),const SizedBox(height:8),f(a,'Address',lines:2),const SizedBox(height:8),f(p,'Phone'),const SizedBox(height:16),const Text('Description / Items',style:TextStyle(fontWeight:FontWeight.bold,fontSize:18)),const SizedBox(height:8),f(desc,'Description'),const SizedBox(height:8),Row(children:[Expanded(child:f(qty,'Qty',num:true)),const SizedBox(width:8),Expanded(child:f(rate,'Unit Price',num:true))]),OutlinedButton.icon(onPressed:ai,icon:const Icon(Icons.add),label:const Text('Add Item')),...items.asMap().entries.map((e)=>ListTile(title:Text(e.value.d),subtitle:Text('${e.value.q} × ${e.value.r}'),trailing:IconButton(icon:const Icon(Icons.close),onPressed:()=>setState(()=>items.removeAt(e.key))))),f(dis,'Discount %',num:true,ch:(_)=>setState((){})),const SizedBox(height:8),f(note,'Custom Notes / Description',lines:3),const SizedBox(height:12),Text('Subtotal: LKR ${sub.toStringAsFixed(2)}\nDiscount: LKR ${(sub*dp/100).toStringAsFixed(2)}\nTOTAL: LKR ${total.toStringAsFixed(2)}',textAlign:TextAlign.right,style:const TextStyle(fontSize:17,fontWeight:FontWeight.bold)),const SizedBox(height:12),const ListTile(leading:Icon(Icons.draw,color:gold),title:Text('Authorized Signature'),subtitle:Text('Dinuth • D&S Cleaning Service')),FilledButton(style:FilledButton.styleFrom(backgroundColor:gold,foregroundColor:Colors.black,padding:const EdgeInsets.all(15)),onPressed:sv,child:Text('Save & Preview ${widget.t}'))]));}
Future<void>pdf(Dc x)async{final b=await rootBundle.load('assets/ds_logo.jpg'),im=pw.MemoryImage(b.buffer.asUint8List()),doc=pw.Document();doc.addPage(pw.MultiPage(pageFormat:PdfPageFormat.a4,build:(_)=>[pw.Row(mainAxisAlignment:pw.MainAxisAlignment.spaceBetween,children:[pw.Image(im,width:100,height:100),pw.Column(crossAxisAlignment:pw.CrossAxisAlignment.end,children:[pw.Text(x.t.toUpperCase(),style:pw.TextStyle(fontSize:25,fontWeight:pw.FontWeight.bold)),pw.Text(x.id),pw.Text('Date: ${x.date}'),if(x.valid.isNotEmpty)pw.Text('Valid Until: ${x.valid}')])]),pw.Divider(),pw.Text('D&S CLEANING SERVICE',style:pw.TextStyle(fontWeight:pw.FontWeight.bold)),pw.Text('Home Maintenance'),pw.SizedBox(height:15),pw.Text('Customer: ${x.c}'),if(x.a.isNotEmpty)pw.Text(x.a),if(x.p.isNotEmpty)pw.Text(x.p),pw.SizedBox(height:15),pw.TableHelper.fromTextArray(headers:['Description','Qty','Unit Price','Amount'],data:x.items.map((i)=>[i.d,i.q.toString(),i.r.toStringAsFixed(2),i.a.toStringAsFixed(2)]).toList()),pw.SizedBox(height:15),pw.Align(alignment:pw.Alignment.centerRight,child:pw.Text('Subtotal: ${x.sub.toStringAsFixed(2)}\nDiscount (${x.dis}%): ${(x.sub*x.dis/100).toStringAsFixed(2)}\nTOTAL (LKR): ${x.total.toStringAsFixed(2)}',textAlign:pw.TextAlign.right,style:pw.TextStyle(fontWeight:pw.FontWeight.bold))),if(x.note.isNotEmpty)...[pw.SizedBox(height:20),pw.Text('Notes / Description',style:pw.TextStyle(fontWeight:pw.FontWeight.bold)),pw.Text(x.note)],pw.SizedBox(height:35),pw.Align(alignment:pw.Alignment.centerRight,child:pw.Column(children:[pw.Text('Dinuth',style:pw.TextStyle(fontSize:23,fontStyle:pw.FontStyle.italic)),pw.Text('________________'),pw.Text('Authorized Signature'),pw.Text('D&S Cleaning Service')]))]));await Printing.layoutPdf(onLayout:(_)=>doc.save(),name:'${x.id}.pdf');}